Tracker:AddItems("items/items.json")
Tracker:AddItems("items/Seeds.json")
Tracker:AddItems("items/settings.json")
Tracker:AddItems("items/fishsanity_items.json")
Tracker:AddItems("items/museumsanity_items.json")
Tracker:AddItems("items/cropsanity_items.json")
Tracker:AddItems("items/festival_items.json")
Tracker:AddItems("items/quests_items.json")
Tracker:AddItems("items/arcade_items.json")
Tracker:AddItems("items/shipsanity_items.json")
Tracker:AddItems("items/cooksanity_items.json")
Tracker:AddItems("items/recipes.json")
Tracker:AddItems("items/skills_items.json")
Tracker:AddItems("items/books_items.json")
-- Generated category toggles (one item per AP location id used as a visibility flag)
Tracker:AddItems("items/friendsanity_items.json")
Tracker:AddItems("items/eatsanity_items.json")
Tracker:AddItems("items/craftsanity_items.json")
Tracker:AddItems("items/hatsanity_items.json")
Tracker:AddItems("items/monstersanity_items.json")
Tracker:AddItems("items/walnutsanity_items.json")
Tracker:AddItems("items/walnut_purchase_items.json")
Tracker:AddItems("items/chefsanity_items.json")
Tracker:AddItems("items/moviesanity_items.json")
Tracker:AddItems("items/endgame_items.json")
Tracker:AddItems("items/babies_items.json")
Tracker:AddItems("items/secretsanity_items.json")
Tracker:AddItems("items/buildings_items.json")
Tracker:AddItems("items/mine_elevators_items.json")
Tracker:AddItems("items/tool_upgrades_items.json")
Tracker:AddItems("items/story_checks_items.json")
Tracker:AddItems("items/craftsanity_recipes_items.json")

ScriptHost:LoadScript("scripts/logic.lua")

Tracker:AddLocations("locations/CommunityCenter.json")
Tracker:AddLocations("locations/World.json")
Tracker:AddLocations("locations/Quests.json")
Tracker:AddLocations("locations/Cropsanity.json")
Tracker:AddLocations("locations/Fishsanity.json")
Tracker:AddLocations("locations/Museum_Donations.json")
Tracker:AddLocations("locations/Museum_Milestones.json")
Tracker:AddLocations("locations/Boards.json")
Tracker:AddLocations("locations/Desert_Festival.json")
Tracker:AddLocations("locations/Night_Market.json")
Tracker:AddLocations("locations/Fishing_Festivals.json")
Tracker:AddLocations("locations/Town_Festivals.json")
Tracker:AddLocations("locations/Arcades.json")
Tracker:AddLocations("locations/Cooksanity.json")
Tracker:AddLocations("locations/Skills_Masteries.json")
Tracker:AddLocations("locations/Booksanity.json")
-- Generated category locations
Tracker:AddLocations("locations/Friendsanity.json")
Tracker:AddLocations("locations/Eatsanity.json")
Tracker:AddLocations("locations/Craftsanity.json")
Tracker:AddLocations("locations/Hatsanity.json")
Tracker:AddLocations("locations/Monstersanity.json")
Tracker:AddLocations("locations/Walnutsanity.json")
Tracker:AddLocations("locations/Walnut_Purchase.json")
Tracker:AddLocations("locations/Chefsanity.json")
Tracker:AddLocations("locations/Moviesanity.json")
Tracker:AddLocations("locations/Endgame.json")
Tracker:AddLocations("locations/Babies.json")
Tracker:AddLocations("locations/Secretsanity.json")
Tracker:AddLocations("locations/Buildings.json")
Tracker:AddLocations("locations/Mine_Elevators.json")
Tracker:AddLocations("locations/Tool_Upgrades.json")
Tracker:AddLocations("locations/Story_Checks.json")

Tracker:AddLayouts("layouts/item_grids.json")
Tracker:AddLayouts("layouts/tool_grid.json")
Tracker:AddLayouts("layouts/island_grid.json")
Tracker:AddLayouts("layouts/settings.json")
Tracker:AddLayouts("layouts/tracker.json")

Tracker:AddMaps("maps/maps.json")

Tracker:AddLayouts("layouts/seeds.json")

ScriptHost:LoadScript("scripts/watches.lua")

updateIslandTracking()

if PopVersion and PopVersion >= "0.18.0" then
  ScriptHost:LoadScript("scripts/autotracking.lua")
end